name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      - run: PYTHONPATH=src python -c "from typesnake.lexer import lexer; from typesnake.parser_1 import parser; from typesnake.semantic_analyzer import semantic_analyzer; from typesnake.code_generator import generate_code; from typesnake.symbol_table import SymbolTable; print('OK')"
